[package]
name = "follows_types"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "follows_types"

[dependencies]
hdk = { workspace = true }
serde = { workspace = true }
hc_link_pagination = { workspace = true }
