[workspace]
resolver = "2"
members = [
    "dnas/clutter/integrity_zomes/profiles",
    "dnas/clutter/coordinator_zomes/profiles",
    "dnas/clutter/zomes/mews",
]

[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"
