[package]
name = "mews_integrity"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "mews_integrity"

[dependencies]
hdi = { workspace = true }
hdk = { workspace = true }
serde = { workspace = true }
prefix_index = { git = "https://github.com/jost-s/holochain-prefix-index", branch = "build/upgrade-to-holochain-0.2", module = "lib/prefix_index" }
mews_types = { workspace = true }