[package]
edition = "2021"
name = "mews"
version = "0.0.1"

[lib]
crate-type = ["cdylib", "rlib"]
name = "mews"

[dependencies]
chrono = {version = "0.4", features = ["serde"]}
derive_more = "0"
regex = "1"
serde = "1"

hdk = {version = "0.0.138", features = ["encoding"]}
