[package]
edition = "2021"
name = "mews_integrity"
version = "0.0.1"

[lib]
crate-type = ["cdylib", "rlib"]
name = "mews_integrity"

[dependencies]
serde = "1"
strum = "0.24"
strum_macros = "0.24"

hdi = "=0.1.10"
