[package]
name = "hc_link_pagination"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "hc_link_pagination"

[dependencies]
hdk = { workspace = true }
serde = { workspace = true }
