[package]
name = "follows"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "follows"

[dependencies]
hdk = { workspace = true }

serde = { workspace = true }

follows_integrity = { workspace = true } 
