/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseAgentProfile: typeof import('./src/components/BaseAgentProfile.vue')['default']
    BaseAgentProfileLinkAvatar: typeof import('./src/components/BaseAgentProfileLinkAvatar.vue')['default']
    BaseAgentProfileLinkName: typeof import('./src/components/BaseAgentProfileLinkName.vue')['default']
    BaseAgentProfileName: typeof import('./src/components/BaseAgentProfileName.vue')['default']
    BaseAgentProfileNameLarge: typeof import('./src/components/BaseAgentProfileNameLarge.vue')['default']
    BaseAgentProfilePopupContent: typeof import('./src/components/BaseAgentProfilePopupContent.vue')['default']
    BaseAgentProfilesList: typeof import('./src/components/BaseAgentProfilesList.vue')['default']
    BaseAgentProfilesListItem: typeof import('./src/components/BaseAgentProfilesListItem.vue')['default']
    BaseButtonBack: typeof import('./src/components/BaseButtonBack.vue')['default']
    BaseConfirmDialog: typeof import('./src/components/BaseConfirmDialog.vue')['default']
    BaseEmbedMew: typeof import('./src/components/BaseEmbedMew.vue')['default']
    BaseEmptyMewsFeed: typeof import('./src/components/BaseEmptyMewsFeed.vue')['default']
    BaseLinkProfilePopup: typeof import('./src/components/BaseLinkProfilePopup.vue')['default']
    BaseMewContent: typeof import('./src/components/BaseMewContent.vue')['default']
    BaseMewContentTag: typeof import('./src/components/BaseMewContentTag.vue')['default']
    BaseMewList: typeof import('./src/components/BaseMewList.vue')['default']
    BaseMewListItem: typeof import('./src/components/BaseMewListItem.vue')['default']
    BaseMewListItemSkeleton: typeof import('./src/components/BaseMewListItemSkeleton.vue')['default']
    BaseMewListSkeleton: typeof import('./src/components/BaseMewListSkeleton.vue')['default']
    BaseNotification: typeof import('./src/components/BaseNotification.vue')['default']
    BaseProfileSkeleton: typeof import('./src/components/BaseProfileSkeleton.vue')['default']
    BaseSiteMenu: typeof import('./src/components/BaseSiteMenu.vue')['default']
    BaseTimestamp: typeof import('./src/components/BaseTimestamp.vue')['default']
    ButtonFollow: typeof import('./src/components/ButtonFollow.vue')['default']
    CreateMewDialog: typeof import('./src/components/CreateMewDialog.vue')['default']
    CreateMewForm: typeof import('./src/components/CreateMewForm.vue')['default']
    CreateMewInput: typeof import('./src/components/CreateMewInput.vue')['default']
    CreateProfileIfNotFoundDialog: typeof import('./src/components/CreateProfileIfNotFoundDialog.vue')['default']
    HoloLogin: typeof import('./src/components/HoloLogin.vue')['default']
    IconIonChatbubbleoutline: typeof import('~icons/ion/chatbubbleoutline')['default']
    IconIonChatbubbleOutline: typeof import('~icons/ion/chatbubble-outline')['default']
    LinkProfilePopup: typeof import('./src/components/LinkProfilePopup.vue')['default']
    ProfilePopupContent: typeof import('./src/components/ProfilePopupContent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchEverythingDialog: typeof import('./src/components/SearchEverythingDialog.vue')['default']
    SearchEverythingDialogInput: typeof import('./src/components/SearchEverythingDialogInput.vue')['default']
  }
}
