/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AgentProfileDetail: typeof import('./src/components/AgentProfileDetail.vue')['default']
    BaseAgentProfile: typeof import('./src/components/BaseAgentProfile.vue')['default']
    BaseAgentProfileDetail: typeof import('./src/components/BaseAgentProfileDetail.vue')['default']
    BaseAgentProfileDetailSkeleton: typeof import('./src/components/BaseAgentProfileDetailSkeleton.vue')['default']
    BaseAgentProfileLinkAvatar: typeof import('./src/components/BaseAgentProfileLinkAvatar.vue')['default']
    BaseAgentProfileLinkName: typeof import('./src/components/BaseAgentProfileLinkName.vue')['default']
    BaseAgentProfileList: typeof import('./src/components/BaseAgentProfileList.vue')['default']
    BaseAgentProfileListItem: typeof import('./src/components/BaseAgentProfileListItem.vue')['default']
    BaseAgentProfileListItemSkeleton: typeof import('./src/components/BaseAgentProfileListItemSkeleton.vue')['default']
    BaseAgentProfileName: typeof import('./src/components/BaseAgentProfileName.vue')['default']
    BaseAgentProfileNameLarge: typeof import('./src/components/BaseAgentProfileNameLarge.vue')['default']
    BaseAgentProfileNameSkeleton: typeof import('./src/components/BaseAgentProfileNameSkeleton.vue')['default']
    BaseAvatarInput: typeof import('./src/components/BaseAvatarInput.vue')['default']
    BaseButtonBack: typeof import('./src/components/BaseButtonBack.vue')['default']
    BaseConfirmDialog: typeof import('./src/components/BaseConfirmDialog.vue')['default']
    BaseDialog: typeof import('./src/components/BaseDialog.vue')['default']
    BaseEditAgentProfileForm: typeof import('./src/components/BaseEditAgentProfileForm.vue')['default']
    BaseEmbedMew: typeof import('./src/components/BaseEmbedMew.vue')['default']
    BaseEmptyList: typeof import('./src/components/BaseEmptyList.vue')['default']
    BaseIconTongue: typeof import('./src/components/BaseIconTongue.vue')['default']
    BaseInfiniteScroll: typeof import('./src/components/BaseInfiniteScroll.vue')['default']
    BaseLinkProfilePopup: typeof import('./src/components/BaseLinkProfilePopup.vue')['default']
    BaseList: typeof import('./src/components/BaseList.vue')['default']
    BaseListSkeleton: typeof import('./src/components/BaseListSkeleton.vue')['default']
    BaseMewContent: typeof import('./src/components/BaseMewContent.vue')['default']
    BaseMewContentTag: typeof import('./src/components/BaseMewContentTag.vue')['default']
    BaseMewListItem: typeof import('./src/components/BaseMewListItem.vue')['default']
    BaseMewListItemSkeleton: typeof import('./src/components/BaseMewListItemSkeleton.vue')['default']
    BaseNotification: typeof import('./src/components/BaseNotification.vue')['default']
    BaseSiteMenu: typeof import('./src/components/BaseSiteMenu.vue')['default']
    BaseThemeSelect: typeof import('./src/components/BaseThemeSelect.vue')['default']
    BaseTimestamp: typeof import('./src/components/BaseTimestamp.vue')['default']
    BaseTooltip: typeof import('./src/components/BaseTooltip.vue')['default']
    ButtonFollow: typeof import('./src/components/ButtonFollow.vue')['default']
    CreateMewDialog: typeof import('./src/components/CreateMewDialog.vue')['default']
    CreateMewInput: typeof import('./src/components/CreateMewInput.vue')['default']
    CreateProfileIfNotFoundDialog: typeof import('./src/components/CreateProfileIfNotFoundDialog.vue')['default']
    CreatorsListDialog: typeof import('./src/components/CreatorsListDialog.vue')['default']
    EditAgentProfileDialog: typeof import('./src/components/EditAgentProfileDialog.vue')['default']
    FollowersListDialog: typeof import('./src/components/FollowersListDialog.vue')['default']
    HoloLogin: typeof import('./src/components/HoloLogin.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchEverythingDialog: typeof import('./src/components/SearchEverythingDialog.vue')['default']
    SearchEverythingDialogInput: typeof import('./src/components/SearchEverythingDialogInput.vue')['default']
    ToastNotices: typeof import('./src/components/ToastNotices.vue')['default']
  }
}
