[package]
edition = "2021"
name = "mews"
version = "0.0.1"

[lib]
crate-type = ["cdylib", "rlib"]
name = "mews"

[dependencies]
derive_more = "0"
regex = "1"
serde = "1"
chrono = { version = "0.4.22", default-features = false, features = ["clock", "std", "oldtime", "serde"] }
mews_integrity = {path = "../../integrity_zomes/mews"}
hdk = {version = "0.0.163", features = ["encoding"]}
hc_time_index = {git = "https://github.com/mattyg/holochain-time-index.git", branch = "develop", package = "hc_time_index"}