name: CI

on:
  pull_request:
  push:
    branches:
      - "develop"
      - "main"

concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install nix
        uses: cachix/install-nix-action@v27

      # - name: Set up cachix
      #   uses: cachix/cachix-action@v15
      #   with:
      #     name: holochain-ci

      - name: Restore cargo and build from cache
        uses: actions/cache/restore@v3
        with:
          path: |
            .cargo
            target
          key: ${{ runner.os }}-build-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-
      
      - name: Install nix packages
        uses: nicknovitski/nix-develop@v1

      - name: Install JS packages
        run: npm ci

      - name: Clippy
        run: npm run cargo:clippy

      - name: Check rust formatting
        run: npm run cargo:fmt:check

      - name: Build Happ
        run: npm run build:happ

      - name: Save cargo and build to cache
        uses: actions/cache/save@v3
        with:
          path: |
            .cargo
            target
          key: ${{ runner.os }}-build-${{ hashFiles('Cargo.lock') }}

      - name: Test with tryorama
        run: npm run test
