name: CI

on:
  pull_request:
  push:
    branches:
      - "main"

concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install nix
        uses: cachix/install-nix-action@v19

      - name: Set up cachix
        uses: cachix/cachix-action@v12
        with:
          name: geekgene
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          pathsToPush:

      - name: Cache Cargo and Rust Build
        uses: actions/cache@v2
        with:
          path: |
            .cargo
            target
          key: ${{ runner.os }}-build-${{ hashFiles('Cargo.lock') }}

      - name: Build Happ
        run: nix develop -c $SHELL -c "npm ci && npm run build:happ"

      - name: Test with tryorama
        run: nix develop -c $SHELL -c "npm test"
